# Site settings
title: "Liv's Fungi Forest"
bye_message: "Thx!"
baseurl: "/livinabsurdism"
url: "http://livinabsurdism.github.io"
disqus: gjuniioor

# Header settings
nick: "livinabsurdism"
source_code:
    server: "github.com"
    nick: "livinabsurdism"
fingerprint_key: "ENTER GPG KEY HERE"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
