# Site settings
title: "Liv's Fungi Forest"
bye_message: "Thx!"
baseurl: ""
url: "http://livinabsurdism.github.io"
disqus: gjuniioor

# Header settings
nick: "livinabsurdism"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "livinabsurdism"
blog:
    server: "wordpress.com"
    nick: "gjuniioor"
fingerprint_key: "ENTER GPG KEY HERE"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
